name: Imperator.co
storage_path: /root/.walrus_{{ env_node }}-{{ node_number }}/db
protocol_key_pair:
  path: /root/.walrus_{{ env_node }}-{{ node_number }}/config/protocol.key
network_key_pair:
  path: /root/.walrus_{{ env_node }}-{{ node_number }}/config/network.key
public_host: {{ lookup('vars', client)[node_number]['dns_storage'] }}
public_port: {{ lookup('vars', client)[node_number]['port_storage'] }}
metrics_address: 0.0.0.0:{{ lookup('vars', client)[node_number]['port_storage_metrics'] }}
rest_api_address: 0.0.0.0:{{ lookup('vars', client)[node_number]['port_storage'] }}
rest_graceful_shutdown_period_secs: 60
sui:
  rpc: https://mysten-rpc.testnet.sui.io:443
  system_object: "0x98ebc47370603fe81d9e15491b2f1443d619d1dab720d586e429ed233e1255c1"
  staking_object: "0x20266a17b4f1a216727f3eef5772f8d486a9e3b5e319af80a5b75809c035561d"
  event_polling_interval_millis: 400
  wallet_config: /root/.walrus_{{ env_node }}-{{ node_number }}/config/sui_config.yaml
  gas_budget: 500000000
commission_rate: 0
voting_params:
  storage_price: 100
  write_price: 2000
  node_capacity: {{ lookup('vars', client)[node_number]['node_capacity'] }}
metrics_push:
  push_url: https://walrus-metrics-testnet.mystenlabs.com/publish/metrics